export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { inter } from "./font/font";
import { SpeedInsights } from "@vercel/speed-insights/next";
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body class="overflow-hidden">
        {children} <SpeedInsights />
      </body>
    </html>
  );
}
