export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import { inter } from "./font/font";
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body class="overflow-hidden">{children}</body>
    </html>
  );
}
